host         : 0.0.0.0
title        : "NightScript Domain"
repo         : "NightYoshi370/NightYoshi370.github.io"
description  : "This website was made to document things I've accomplished over the years. Maybe you'll find something interesting here?"
markdown_ext : "markdown,mkdown,mkdn,mkd,md,html"

compress_html:
  comments: ["<!-- ", " -->"]

themes:
  - 'mario-yellow'
  - 'mario-red'
  - 'mario-blue'
  - 'mario-green'
  - 'light'
  - 'dark'
  - 'discord'
  - 'default'

defaults:
  - scope:
      path: "pages"
      type: pages
    values:
      permalink: /:basename:output_ext
      layout: "default"